name: ReBarDxe EDK2

on:
  push:
    branches: [ "master", "stock-baseline" ]
  pull_request:
    branches: [ "master", "stock-baseline" ]
env:
  TARGET: RELEASE
  TARGET_ARCH: X64

jobs:
  rebardxe-windows:
    runs-on: windows-2022

    env:
      TOOL_CHAIN_TAG: VS2022
      _CL_: "/wd4319 /wd4311 /wd4312 /wd4303 /wd4302 /wd4267 /wd4244 /wd4068 /wd4477"
      CL: "/wd4319 /wd4311 /wd4312 /wd4303 /wd4302 /wd4267 /wd4244 /wd4068 /wd4477"

    steps:
    - uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - run: pip install pefile

    - name: Support long filenames
      run: git config --system core.longpaths true

    - name: Set up MSVC environment
      uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: x64

    - name: Install NASM
      shell: powershell
      run: |
        if (!(Test-Path "C:\nasm\nasm.exe")) {
          New-Item -ItemType Directory -Force -Path "C:\nasm"
          Invoke-WebRequest -Uri "https://www.nasm.us/pub/nasm/releasebuilds/2.15.05/win64/nasm-2.15.05-win64.zip" -OutFile "C:\nasm\nasm.zip"
          Expand-Archive -Path "C:\nasm\nasm.zip" -DestinationPath "C:\nasm\temp" -Force
          Copy-Item "C:\nasm\temp\nasm-2.15.05\*" "C:\nasm\" -Force
        }
        echo "C:\nasm" >> $env:GITHUB_PATH
        echo "NASM_PREFIX=C:\nasm\" >> $env:GITHUB_ENV

    - name: Download edk2
      uses: actions/checkout@v4
      with:
        repository: 'tianocore/edk2'
        ref: 'edk2-stable202508'
        submodules: 'recursive'

    - name: Download RebarUEFI
      uses: actions/checkout@v4
      with:
        path: '.\ReBarUEFI\'

    - name: Setup & Build BaseTools
      shell: cmd
      run: |
        call edksetup.bat Rebuild

    - name: Build RebarDxe
      shell: cmd
      run: |
        call edksetup.bat
        python .\ReBarUEFI\ReBarDxe\buildffs.py RELEASE

    - name: Upload ReBarDxe artifact (Windows)
      uses: actions/upload-artifact@v4
      with:
        name: ReBarDxe (built on Windows)
        path: |
          Build/ReBarUEFI/RELEASE_VS2022/X64/ReBarDxe.efi
          Build/ReBarUEFI/RELEASE_VS2022/X64/ReBarDxe.ffs


  rebardxe-linux:
    runs-on: ubuntu-24.04

    env:
      TOOL_CHAIN_TAG: GCC

    steps:
    - uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - run: pip install pefile

    - name: Download edk2
      uses: actions/checkout@v4
      with:
        repository: 'tianocore/edk2'
        ref: 'edk2-stable202508'
        submodules: 'recursive'
        path: '.'

    - name: Download RebarUEFI
      uses: actions/checkout@v4
      with:
        path: './ReBarUEFI/'

    - name: Install dependencies
      run: sudo apt update && sudo apt install -y build-essential uuid-dev iasl git nasm python-is-python3

    - name: Build Base Tools
      run: make -C ./BaseTools/

    - name: Setup EDK2
      run: bash -c "source edksetup.sh"

    - name: Build RebarDxe
      run: ./ReBarUEFI/.github/workflows/buildffs.sh

    - name: Upload ReBarDxe artifact (Linux)
      uses: actions/upload-artifact@v4
      with:
        name: ReBarDxe (built on Linux)
        path: |
          Build/ReBarUEFI/RELEASE_GCC/X64/ReBarDxe.efi
          Build/ReBarUEFI/RELEASE_GCC/X64/ReBarDxe.ffs
